---
title: "PI3K_Signature"
author: "Shelley MacNeil"
date: "July 11, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the RNA-seq PI3K Signature
```{r }
source("C:/Users/10002293/PI3K_Signature_Validation/scripts/Key_ASSIGN_functions_balancedsig.R")
source("C:/Users/10002293/PI3K_Signature_Validation/scripts/CommonRFunctions.R")
working_dir="~/Documents/PhDProjects/PI3K_Signature_Validation/data/"
setwd(working_dir)
pi3k_gfp = readRDS("~/Documents/PhDProjects/PI3K_Signature_Validation/data/gfp_pi3k.rds")
dim(pi3k_gfp)
colnames(pi3k_gfp)

View(pi3k_gfp)
pi3k_gfp_f <-pi3k_gfp[apply(pi3k_gfp[,1:17]==0,1,mean) < 0.85,]
dim(pi3k_gfp_f)
View(pi3k_gfp_f)
write.table(pi3k_gfp_f, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/pi3k_gfp_tmg_with6.txt", col.names=NA,sep='\t',quote=F)

pi3k_f_6=pi3k_gfp_f[,10:18]
write.table(pi3k_f_6, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/pi3k_only_tmg_with6.txt", col.names=NA,sep='\t',quote=F)

gfp_f_6=pi3k_gfp_f[,1:9]
write.table(gfp_f_6, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/gfp_only_tmg_with6.txt", col.names=NA,sep='\t',quote=F)

# now remove the bad GFPS
pi3k_gfp_rm5610_both=pi3k_gfp_f[,-c(5,6,9)]
View(pi3k_gfp_rm5610_both)
dim(pi3k_gfp_rm5610_both)

# I don't think i filtered when I wrote these out..
pi3k_rm5610_only= pi3k_gfp_rm5610_both[,7:15]
gfp_rm5610_only= pi3k_gfp_rm5610_both[,1:6]
write.table(pi3k_gfp_rm5610_both, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/pi3k_gfp_rm5610_both.txt", col.names=NA,sep='\t',quote=F)
write.table(pi3k_rm5610_only, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/pi3k_rm5610_only.txt", col.names=NA,sep='\t',quote=F)
write.table(gfp_rm5610_only, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/gfp_rm5610_only.txt", col.names=NA,sep='\t',quote=F)

#pi3k_gfp=pi3k_gfp[,-6]
# filter low expressing genes


```

Plot PI3K gene
```{r}

pi3k_gene_tpm = as.matrix(pi3k_gfp_f["PIK3CA",])
her2_gene_tpm = as.matrix(pi3k_gfp_f["ERBB2",])

dim(pi3k_gene_tpm)
boxplot(pi3k_gene_tpm[1:9],pi3k_gene_tpm[10:18], names=c("GFP", "PI3K"), main= "RNA-seq Values for PIK3CA (All GFPs)")
tttest=t.test(pi3k_gene_tpm[1:9],pi3k_gene_tpm[10:18])
title(sub="P-value = 0.007 ", adj=1, line=3, font=1)


boxplot(her2_gene_tpm[1:9],her2_gene_tpm[10:18], names=c("GFP", "ERBB2"))
t.test(her2_gene_tpm[1:9],her2_gene_tpm[10:18])

dim(pi3k_gfp_rm5610_both)
pi3k_gene_tpm_rm = as.matrix(pi3k_gfp_rm5610_both["PIK3CA",])
boxplot(pi3k_gene_tpm_rm[1:9],pi3k_gene_tpm_rm[10:18], names=c("GFP", "PIK3CA"), main= "RNA-seq Values for PIK3CA (Rm GFP 5,6,10)")
t.test(pi3k_gene_tpm_rm[1:9],pi3k_gene_tpm_rm[10:18])
title(sub="P-value = 0.142 ", adj=1, line=3, font=1)

```



DE analysis
```{r}
library(limma)
#colnames_pi3k=as.data.frame(colnames(pi3k_gfp_f))
colnames_pi3k=as.data.frame(colnames(pi3k_gfp_rm5610_both))

colnames_pi3k
classes=(c("control","control","control","control","control","control","control","control","control", "pi3k", "pi3k","pi3k","pi3k","pi3k","pi3k","pi3k", "pi3k", "pi3k"))
classes2=(c("control","control","control","control","control","control", "pi3k", "pi3k","pi3k","pi3k","pi3k","pi3k","pi3k", "pi3k", "pi3k"))
classes=as.matrix(classes)
View(classes)
classes_all=cbind(colnames_pi3k,classes)
classes_rm5610=cbind(colnames_pi3k,classes2)
classes_rm5610

rownames(classes)=classes[,1]
classes

design <- model.matrix(~ factor(classes[,2]))
design
colnames(design) <- c("ALL", "1vs2")
fit <- lmFit(pi3k_gfp_f, design)
fit
fit <- eBayes(fit)
View(fit)
dim(fit)
DEgenes1 <- topTable(fit,coef=2, adjust.method = "BH", number = 20401, sort.by = "p")
View(DEgenes1)
DEgenes_s <- DEgenes1[ which(DEgenes1$adj.P.Val < 0.01),]

View(DEgenes_s)
just_genes=as.data.frame(rownames(DEgenes_s))
View(just_genes)
write.table(just_genes, "~/Documents/PhDProjects/PI3K_Signature_Validation/results/DE_genes_PI3K_Signature.txt",col.names=NA,sep='\t',quote=F)

res = decideTests(fit, adjust.method = "BH", p.value = 0.01)
View(res)
vennDiagram(res)

# what about PI3k?
pi3k_gene =DEgenes1[ "PIK3CA",]
pi3k_gene


# now try without GFP 5,6,10
pi3k_gfp_rm5610_both

colnames_pi3k=as.data.frame(colnames(pi3k_gfp_rm5610_both))
colnames_pi3k
classes=(c("control","control","control","control","control","control", "pi3k", "pi3k","pi3k","pi3k","pi3k","pi3k","pi3k", "pi3k", "pi3k"))
classes=as.matrix(classes)
classes
classes=cbind(colnames_pi3k,classes)
rownames(classes)=classes[,1]
classes

design <- model.matrix(~ factor(classes[,2]))
design
colnames(design) <- c("ALL", "gfpvspi3k")
fit <- lmFit(pi3k_gfp_rm5610_both, design)
View(fit)
fit <- eBayes(fit)
View(fit)
dim(fit)
DEgenes1 <- topTable(fit,coef=2, adjust.method = "BH", number = 20401, sort.by = "p")
View(DEgenes1)
DEgenes_s <- DEgenes1[ which(DEgenes1$adj.P.Val < 0.01),]
dim(DEgenes_s)
just_genes=as.data.frame(rownames(DEgenes_s))
dim(just_genes)
write.table(just_genes, "~/Documents/PhDProjects/PI3K_Signature_Validation/results/DE_genes_PI3K_Signature_rm5610.txt",col.names=NA,sep='\t',quote=F)



```

Read in the binReg results
```{r}
setwd("C:/Users/10002293/Desktop/TCGA_probabilities/")
binreg_files=system("ls", intern=TRUE)
binreg_files
length(binreg_files)
library(data.table)

for(i in 1:length(binreg_files)){
  ###reading in the filess one at a time
  #f= as.matrix(read.table(binreg_files[1], stringsAsFactors = FALSE, header=1,sep='\t', quote=""))
  f <- read.delim(binreg_files[i], quote="")
  f= f[31:1149,c(2,5)]
  #f= f[35:89,c(2,5)]
  is.numeric(f[2])
  rownames(f)=f[,1]
  colnames(f)[2]=c(gsub('\\..*$','',binreg_files[i]))
  class(f)
  f[,2]=as.numeric( f[,2])
  is.numeric( f[,2])
  var_name=gsub('\\..*$','',binreg_files[i])
  print(var_name)
  assign(var_name, f) 
}  


typeof(probabilities_100_DWD)
is.numeric(probabilities_100_DWD)
is.numeric(probabilities_100_DWD[,2])

class(probabilities_100_DWD)
#icbp_prob_matix <- cbind(probabilities_PI3K_5[2],probabilities_PI3K_10[2],probabilities_PI3K_15[2],probabilities_PI3K_20[2],probabilities_PI3K_25[2], probabilities_PI3K_30[2],probabilities_PI3K_50[2],probabilities_PI3K_75[2],probabilities_PI3K_100[2],probabilities_PI3K_125[2],probabilities_PI3K_150[2],probabilities_PI3K_175[2],probabilities_PI3K_200[2],probabilities_PI3K_225[2],probabilities_PI3K_250[2],probabilities_PI3K_275[2],probabilities_PI3K_350[2],probabilities_PI3K_400[2],probabilities_PI3K_450[2],probabilities_PI3K_475[2],probabilities_PI3K_500[2]) 

tcga_prob_matix <- cbind(probabilities_100_DWD[2],probabilities_100_SHIFTSCALE[2],probabilities_200_DWD[2],probabilities_200_SHIFTSCALE[2],probabilities_300_DWD[2],probabilities_300_SHIFTSCALE[2],probabilities_400_DWD[2],probabilities_400_SHIFTSCALE[2],probabilities_500_DWD[2],probabilities_500_SHIFTSCALE[2],probabilities_75_DWD[2],probabilities_75_SHIFTSCALE[2])

class(tcga_prob_matix)
typeof(tcga_prob_matix)
View(tcga_prob_matix)
cor(tcga_prob_matix)
dim(tcga_prob_matix)
```

Read in the ICBP protein data and ICBP drug data
```{r}

data_dir <- "C:/Users/10002293/PI3K_Signature_Validation/filesharing/"
icbp_drug_response<-paste(data_dir,"ICBP_drugs.txt",sep="/")
ICBP_drugs<-read.delim(icbp_drug_response, header=1, sep='\t',row.names=1, stringsAsFactors = FALSE)
ICBP_drugs_2=ICBP_drugs[,11:100]
View(ICBP_drugs_2)
class(ICBP_drugs_2)
colnames(ICBP_drugs_2)
is.numeric(ICBP_drugs_2)
is.numeric(ICBP_drugs_2[,50])

TCGA_RPPA_path=readFile("C:/Users/10002293/PI3K_Signature_Validation/filesharing/TCGA-BRCA-RBN.") 
TCGA_RPPA_path
is.numeric(TCGA_RPPA_path[,3])

```

Correlate ICBP Drug Data
```{r}

icbp_drug_working=merge_drop(icbp_prob_matix,ICBP_drugs)
icbp_drug=icbp_drug_working[,-11]
View(icbp_drug)
colnames(icbp_drug)
icbp_drug[,1]
icbp_drug[,32]
cor(icbp_drug$probabilities_50_dwd_icbp, icbp_drug$X17.AAG, use="pairwise",method="spearman")

class(icbp_drug)
colnames(icbp_drug)

probs= icbp_drug[,1:14]
#probs = icbp_drug[,1:21]
View(probs)
typeof(probs)
class(probs)
cor(probs)
is.numeric(probs)
is.numeric(probs[,1])
colnames(icbp_drug)

drug= icbp_drug[,25:114]
colnames(drug)
dim(drug)
View(drug)
typeof(drug)
class(drug)

for (i in 1:90){
  print(is.numeric(drug[,i]))
}


cor(drug, use="pairwise",method="spearman")

#cor_drugs_probs=cor(probs, drugs)

drug_prob_corrs=cor(drug, probs, use="pairwise",method="spearman")
drug_prob_corrs=t(drug_prob_corrs)
View(drug_prob_corrs)

#write.table(drug_prob_corrs, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/RNAseq_PI3K_ICBP_Drug_Cors.txt", col.names=NA,sep='\t',quote=F)
#write.table(drug_prob_corrs, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/RNAseq_PI3K_ICBP_Drug_Cors_rm5610.txt", col.names=NA,sep='\t',quote=F)
write.table(drug_prob_corrs, "C:/Users/10002293/PI3K_Signature_Validation/filesharing/PI3K_Drug_Cors_ICBP_Oldsig2.txt", col.names=NA,sep='\t',quote=F)

```

Correlate with ICBP protein data
```{r}

TCGA_rppa=merge_drop(tcga_prob_matix,TCGA_RPPA_path)
View(TCGA_rppa)
colnames(TCGA_rppa)
#icbp=icbp[,-11]

tcga= TCGA_rppa[,4:194]
#icbp=icbp[,-11]


rppa= icbp_rppa[,16:85]
View(rppa)
  
corrs_rppa = cor(icbp,rppa,method="spearman")
#write.table(corrs_rppa, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/RNAseq_PI3K_ICBP_RPPA_Cors.txt", col.names=NA,sep='\t',quote=F)
#write.table(corrs_rppa, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/RNAseq_PI3K_ICBP_RPPA_Cors_rm5610.txt", col.names=NA,sep='\t',quote=F)
write.table(corrs_rppa, "C:/Users/10002293/PI3K_Signature_Validation/filesharing/PI3K_ICBP_RPPA_Cors_Oldsig2.txt", col.names=NA,sep='\t',quote=F)

View(corrs_rppa)
View(icbp_rppa)

```

Correlate binReg with TCGA protein data
```{r}
TCGA_RPPA_path<-read.csv("C:/Users/10002293/PI3K_Signature_Validation/filesharing/TCGA-BRCA-RBN.csv",header=1,check.names = F)
View(TCGA_RPPA_path)
```

# old PI3K signatue 
```{r}

# pi3k only
pi3k_scan<-as.matrix(read.table("~/Documents/PhDProjects/PI3K_Signature_Validation/data/PI3K_Expr_SCAN_Symbol.txt", sep='\t', stringsAsFactors=FALSE, header=1, row.names=1))


# gfp only scan
gfp_pi3k_scan<-as.matrix(read.table("~/Documents/PhDProjects/PI3K_Signature_Validation/data/PI3K_NP63_Control_SCAN_Symbol.txt", sep='\t', stringsAsFactors=FALSE, header=1, row.names=1))

View(gfp_pi3k_scan)

#merge
SCAN_gfp_pi3k_m=t(merge_drop(gfp_pi3k_scan,pi3k_scan))
View(SCAN_gfp_pi3k_m)
SCAN_gfp_pi3k_t <- SCAN_gfp_pi3k_m[order(row.names(SCAN_gfp_pi3k_m)), ]
View(SCAN_gfp_pi3k_t)

rows= c("PI3K1", "PI3K2", "PI3K3", "PI3K4", "PI3K5", "PI3K6", "PI3K7", "PI3K8", "GFP1","GFP2", "GFP3", "GFP4","GFP5", "GFP6", "GFP7", "GFP8", "GFP9", "GFP10", "GFP11" )

rownames(SCAN_gfp_pi3k_t)= rows

View(SCAN_gfp_pi3k_t)
SCAN_gfp_pi3k =t(SCAN_gfp_pi3k_t )
colnames(SCAN_gfp_pi3k)
View(SCAN_gfp_pi3k)

write.table(SCAN_gfp_pi3k, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/PI3K_GFP_SCAN_Symbol_SM.txt", col.names=NA,sep='\t',quote=F)

pi3k_only=SCAN_gfp_pi3k[,1:8]
View(pi3k_only)
write.table(pi3k_only, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/PI3K_Only_SCAN_Symbol_SM.txt", col.names=NA,sep='\t',quote=F)

gfp_only=SCAN_gfp_pi3k[,9:19]
View(gfp_only)
write.table(gfp_only, "~/Documents/PhDProjects/PI3K_Signature_Validation/data/PI3K_GFP_Only_SCAN_Symbol_SM.txt", col.names=NA,sep='\t',quote=F)


# plot the Pi3k gene

pi3k_gene = as.matrix(SCAN_gfp_pi3k["PIK3CA",])
pi3k_gene
rownames(pi3k_gene)
pi3k_gene[9:19]

boxplot(pi3k_gene[9:19],pi3k_gene[1:8], names=c("GFP", "PI3K"), main= "Microarray Values for PIK3CA")
tttest=t.test(pi3k_gene[9:19],pi3k_gene_tpm[1:8])
tttest
title(sub="P-value = 6.603e-09 ", adj=1, line=3, font=1)
```

Run ssGSEA on GFP vs PI3k 
  - do it with all GFPs
  - do with with 5,6,10 removed
```{r}
source("http://bioconductor.org/biocLite.R")
install.packages("GSEABase")
biocLite("GSEABase")
library(GSEABase)
biocLite("GSVAdata")
library(GSVAdata)
data(c2BroadSets)
library(Biobase)
library(genefilter)
library(limma)
library(RColorBrewer)
library(GSVA)
library(gage)

# Get command-line arguments

gmtFile <- "~/Documents/PhDProjects/Data/GMT_Files/c2.cp.v4.0.symbols.gmt"

outputFileName_all <- "~/Documents/PhDProjects/PI3K_Signature_Validation/results/ssGSEA_PI3K_allGFP.txt"
outputFileName_rm <- "~/Documents/PhDProjects/PI3K_Signature_Validation/results/ssGSEA_PI3K_rm5610GFP.txt"

# Within GSEABase, function converts gmt files to an object that has those gene sets (convert gene set collection class, because
# the c2BroadSets gene set collection class uses gene IDs instead of gene symbols); use the getGMT
c2set <- getGmt(gmtFile)


# Run GSVA in ssGSEA format and output to file
gsva_pi3k_all <- gsva(as.matrix(pi3k_gfp_f), c2set, min.sz=10, max.sz=500, verbose=TRUE, rnaseq=TRUE, method="ssgsea")
View(gsvaData)

design_all <- model.matrix(~ factor(classes_all[,2]))
design_all
colnames(design_all) <- c("ALL", "GFPvsPI3K")

all_fit <- lmFit(gsva_pi3k_all, design_all)
all_fit  <- eBayes(all_fit)
GeneSets_pi3k_all <- topTable(all_fit, coef="GFPvsPI3K", number=Inf,adjust.method = "BH", sort.by = "p" )
View(allGeneSets)




# now run without 5,6,or 10

gsvaData_pi3k_rm5610 <- gsva(as.matrix(pi3k_gfp_rm5610_both), c2set, min.sz=10, max.sz=500, verbose=TRUE, rnaseq=TRUE, method="ssgsea")
gsvaData_pi3k_rm5610

design_rm5610 <- model.matrix(~ factor(classes_rm5610[,2]))
design_rm5610
colnames(design_rm5610) <- c("ALL", "GFPvsPI3K")

rm5610_fit <- lmFit(gsvaData_pi3k_rm5610, design_rm5610)
rm5610_fit  <- eBayes(rm5610_fit)

GeneSets_pi3k_rm5610 <- topTable(rm5610_fit, coef="GFPvsPI3K", number=Inf,adjust.method = "BH", sort.by = "p" )

View(GeneSets_pi3k_rm5610)

write.table(GeneSets_pi3k_all, outputFileName_all, col.names=FALSE, quote=FALSE, sep="\t")
write.table(GeneSets_pi3k_rm5610, outputFileName_rm, col.names=FALSE, quote=FALSE, sep="\t")


```



